kind = "web"
previewPath = "/"
title = "Reinado RPG"
version = "1.0.0"
id = "artifacts/reinadorpg"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24205

[services.development]
run = "pnpm --filter @workspace/reinadorpg run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/reinadorpg", "run", "build" ]
publicDir = "artifacts/reinadorpg/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24205"
BASE_PATH = "/"
